---
title: "Day 1 Mini-Project"
author: "By Josh Ivanhoe and Jiong Wei Lua"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
---

```{r}

# INSTRUCTIONS

# You are a seasoned data scientist who has just arrived in Boston. You're looking to go see the sights, but you don't know where they are! Instead of buying a tourist guide like a Muggle, you are going to use your skills in exploratory data analysis and visualization to identify some of the cool spots to visit. 

# Working with your partner, conduct analyses to identify at least THREE cool spots that you want to check out. Use the dashboard format to communicate your findings. You can check e.g. on Google to confirm your findings, but you should include clear commentary indicating how your analysis supports your findings. I've included some of the code from the script we worked on together to help you get started. 

```

```{r}
# You may find the following resources useful: 
# - Your team member(s)! 
# - Data wrangling [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf), 
# - `R` graphics [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf), 
# - [`R` Graphics Cookbook](http://www.cookbook-r.com/Graphs/)
# - [RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
```

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
```

```{r data_prep}
# put your data preparation code here. To get you started, the data preparation we performed in the session previously has already been pasted in. Feel free to add any additional data preparation code needed for your visualizations

listings <- read_csv('../../data/listings.csv')
calendar <- read_csv('../../data/calendar.csv')

source("clean_prices.R")
listings <- clean_prices(listings)
calendar <- clean_prices(calendar)
```

# Visualisations

Column {data-width=500}
-----------------------------------------------------------------------

### For price per person, we looked at the mean by neighbourhood of all booked rentals over the course the year, to ensure there was demand at the listing’s price. For review score, we simply calculated the mean by neighbourhood of all listings.

```{r box_1}

library(ggmap)

boston_coords <- c(left   = -71.1289, 
				   bottom = 42.3201, 
				   right  = -71.0189, 
				   top    = 42.3701)

basemap <- get_map(location = boston_coords,
				maptype = 'terrain')

subset_listings <- listings %>% 
    select(id,price,accommodates,longitude,latitude,neighbourhood) %>%
    mutate(price_per_person = price/accommodates)

ppp_lat_lon <- calendar %>% 
    left_join(subset_listings,
              by = c('listing_id' = 'id')) %>%
    filter(available == FALSE) %>%
    group_by(neighbourhood) %>%
    summarise(average_price_per_person = mean(price_per_person, na.rm = TRUE),
              longitude = mean(longitude,na.rm=TRUE),
              latitude = mean(latitude,na.rm=TRUE)) %>%
    filter(average_price_per_person < 1000) 
    
library(ggmap)
ggmap(basemap) + 
	geom_point(aes(x = longitude, y = latitude, colour = average_price_per_person), 
			   data = ppp_lat_lon, 
			   size = 5) +
    geom_text(aes(x = longitude, y = latitude, label = neighbourhood), size = 2, data = ppp_lat_lon)+
    scale_colour_gradient(high = "green", low="red") +
    xlab('Longitude') +
    ylab('Latitude') + 
    labs(title= 'Average Price Per Person PAID by Airbnb Guests',
         color =' ')

```

Column {data-width=500}
-----------------------------------------------------------------------


###  For both review score and price, there appears to be positive correlation between nearby neighbourhoods, at least qualitatively. It is interesting to note there is complete agreement between our two metrics as to which areas are the most "interesting".



```{r box_3}
# Put the code for a supporting visualization here. This visualization should add context and nuance, but expect the main visualization to convey the bulk of your message. 

# This is not a good visualization -- always remember to include titles and legends. Make yours better! 

neighbourhood_reviews <- listings %>%
  group_by(neighbourhood) %>%
  summarise(latitude=mean(latitude, na.rm=TRUE), 
            longitude=mean(longitude, na.rm=TRUE), 
            review_scores_rating=mean(review_scores_rating, na.rm=TRUE)) %>%
    filter(latitude <= 42.37) %>%
    filter(latitude >=42.32)

ggmap(basemap) +
  geom_point(aes(x=longitude, y=latitude, color=review_scores_rating), 
             data=filter(neighbourhood_reviews, !is.na(review_scores_rating)), 
             size=5) + 
    geom_text(aes(x = longitude, y = latitude, label = neighbourhood), size = 2, data = neighbourhood_reviews) + 
  scale_colour_gradient(high="green", low="red") +
    xlab('Longitude') +
    ylab('Latitude') + 
    labs(title= 'Average Review Score by AirBnb Guests',
         color =' ')

```



